### ISSUE TITLE
Inspect Code step fails to upload results when no code issues exist

### ISSUE THREAD

**Issue by PaxAndromeda** [JetBrains/ReSharper-InspectCode#2]
Re:  https://github.com/YourGirlInSpace/Instar/actions/runs/5313954072/jobs/9620628525

```
Error: Invalid SARIF. Missing 'results' array in run.
    at countResultsInSarif (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:171:19)
    at uploadFiles (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:269:30)
    at async Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:137:12)
    at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:48:30)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:70:9)
```

When no code issues exist, it seems that `results` does not exist which causes the workflow to fail.

**Comment by derigel23** [comment]
@YourGirlInSpace That's a bug not in GitHub Action but in R# CLI tool itself.
I've filed an issue in our tracker [RSRP-492822](https://youtrack.jetbrains.com/issue/RSRP-492822)

**Comment by PaxAndromeda** [comment]
Interesting, good to know!  As a mitigation, I will disable this workflow on my repo until the bug is resolved.  Thanks!

**Comment by PaxAndromeda** [comment]
Hi @derigel23, I see that [RSRP-492822](https://youtrack.jetbrains.com/issue/RSRP-492822) has been marked as fixed.  Is there anything remaining to do on ReShaper-InspectCode for this fix to be operational?

**Comment by derigel23** [comment]
@YourGirlInSpace you need to specify `tool-version: 2023.2.0-EAP06` in the workflow file.
