### ISSUE TITLE
Errors when running

### ISSUE THREAD

**Issue by dlidstrom** [JetBrains/ReSharper-InspectCode#6]
I am seeing this

```
Warning: CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
Warning: Caught an exception while gathering information for telemetry: HttpError: Resource not accessible by integration. Will skip sending status report.
Error: Path does not exist: results.sarif.json
ConfigurationError: Path does not exist: results.sarif.json
    at getSarifFilePaths (D:\a\_actions\github\codeql-action\v2\lib\upload-lib.js:287:15)
    at Object.uploadFromActions (D:\a\_actions\github\codeql-action\v2\lib\upload-lib.js:281:30)
    at run (D:\a\_actions\github\codeql-action\v2\lib\upload-sarif-action.js:56:47)
    at async runWrapper (D:\a\_actions\github\codeql-action\v2\lib\upload-sarif-action.js:84:9)
Warning: Caught an exception while gathering information for telemetry: HttpError: Resource not accessible by integration. Will skip sending status report.
```

I used this action:

```yaml
    - name: Annotate
      uses: JetBrains/ReSharper-InspectCode@v0.3
      with:
        solution: NullableTest/NullableTest.sln
        settings: NullableTest/NullableTest.sln.DotSettings
```

**Comment by derigel23** [comment]
Can you please point to the failed tool run?
Or provide NullableTest/NullableTest.sln solution to test.

**Comment by dlidstrom** [comment]
@derigel23 You can see the error here: https://github.com/DanielLidstromTicket/NullableTest/actions/runs/9744774570
Note that JetBrains action fails while 3rd party action succeeds (but fails with inspection error, quite nicely).

**Comment by derigel23** [comment]
It sees due to an obsolete default version of inspectcode tool.
> Product ReSharper C++ 2023.2 EAP 9 cannot be started because it is expired.

I'll update the action. Also, you can specify the version explicitly.
